project 'WatchDemo.xcodeproj'

# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

platform :ios, '10.0'

target 'WatchDemo' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'SnapKit', '~> 4.0'
end
