project 'CustomFont.xcodeproj'

# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'
target 'CustomFont' do
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
    pod 'SnapKit', '~> 3.2.0'
    
end