project 'BeautyContest.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BeautyContest' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Koloda', '~> 4.0'
  pod 'SnapKit'
  # Pods for BeautyContest

end
